name: Build Reusable

inputs:
  afterBuild:
    required: false
    description: "additional steps to run"
    type: string
  uploadAnalyzerArtifacts:
    required: false
    description: "whether to upload analyzer artifacts"
    type: string
  nodeVersion:
    required: false
    description: "version of Node.js to use"
    type: string
    default: 22.x
  stepName:
    required: true
    description: "name of the step, to be used for the upload artifact unique key "
    type: string

outputs:
  input_step_key:
    description: "normalized step name"
    value: ${{ steps.var.outputs.input_step_key }}

runs:
  using: "composite"
  steps:
    - name: Normalize input step names into path key
      uses: actions/github-script@v7
      id: var
      with:
        script: |
          core.setOutput('input_step_key', '${{ inputs.stepName }}'.toLowerCase().replaceAll(/[/.]/g, '-').trim('-'));

    - name: Setup Node.js (${{ inputs.nodeVersion || env.NODE_LTS_VERSION }})
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.nodeVersion || env.NODE_LTS_VERSION }}
        check-latest: true
    - uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        restore-keys: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}-

    - run: node -v
      shell: bash
    - run: corepack enable
      shell: bash
    - run: pwd
      shell: bash

    - run: pnpm install
      shell: bash
    - run: npm audit signatures # pnpm do not support audit signatures yet
      shell: bash

    - run: pnpm build-stats
      shell: bash

    - run: /bin/bash -c "${{ inputs.afterBuild }}"
      shell: bash

    - name: Upload bundle analyzer artifacts
      uses: actions/upload-artifact@v4
      if: ${{ inputs.uploadAnalyzerArtifacts == 'yes' }}
      with:
        name: webpack bundle analysis stats-${{ steps.var.outputs.input_step_key }}
        path: .next/analyze/*.html
