// This file is supposed to be:
// - generated by introspection of backend API; or
// - provided by backend team.

export type AuthResponse = {
  id_token: string;
  access_token: string;
  expires_in: number;
};
