name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases

    name: Build with ${{ matrix.node-version }}
    uses: ./.github/workflows/build_reusable.yml
    with:
      nodeVersion: ${{ matrix.node-version }}
      stepName: Build
    secrets: inherit

  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build_reusable.yml
        with:
          stepName: Quality

      - if: github.event_name == 'pull_request'
        name: Validate all commits from PR
        run: pnpx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Lint & Format
        run: pnpm biome ci .
      - name: Type checking
        run: pnpm check-types

  test:
    strategy:
      matrix:
        node-version: [22.x]

    name: Run all tests
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/build_reusable.yml
        with:
          stepName: Test

      - name: Run unit tests
        if: false # TODO: Add unit tests
        run: pnpm test

      - name: Install Playwright (used for E2E tests)
        if: false # TODO: Add E2E tests
        run: pnpx playwright install --with-deps

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 7
